### ISSUE TITLE
vimproc_linux64.so is not found on Arch GNU/Linux

### ISSUE THREAD

**Issue by andreicristianpetcu** [Shougo/vimproc.vim#147]
Hi! I use Arch GNU/Linux and I keep getting this error "vimproc's DLL: "/home/andrei/dotfiles/vim/bundle/vimproc.vim/autoload/vimproc_linux64.so" is not found.  Please read :help vimproc and make it."

I use NeoBundle with the recommended install. I tried cloning the project and running "make" but I get this message
$make
make -f make_unix.mak
make[1]: Entering directory '/home/andrei/Dev/vimproc.vim'
cc -W -O2 -Wall -Wno-unused -Wno-unused-parameter -std=gnu99 -pedantic -shared -fPIC -o autoload/vimproc_linux64.so autoload/proc.c -lutil
make[1]: Leaving directory '/home/andrei/Dev/vimproc.vim'

Arch also has an AUR with vimproc but it did not work either. Am I doing something wrong? Here is my vimrc https://github.com/andreicristianpetcu/dotfiles/blob/master/vimrc

Thank you!

**Comment by catesandrew** [comment]
just ran into this issue again, ran `make` and problem fixed.
