### ISSUE TITLE
Vimproc is not installed, while it was installed. 

### ISSUE THREAD

**Issue by ReneFroger** [Shougo/vimproc.vim#150]
**Problem:**
Vimproc is not working.  Vimproc should be working. 

**Setup**

**Environment Information**
- OS: Windows 7 x64
- Vim version: 7.4 

**My whole vimrc:**

> if has('win32') || (' win64')
> set runtimepath=$VIM/.vim,$VIMRUNTIME,$VIM/vimfiles/after,$VIM/.vim/after
> endif
> 
> set nocompatible  
> execute pathogen#infect()
> syntax on
> filetype plugin indent on

Nothing more. 

**Plugins**
There are 3 plugins installed. 
- Pathogen.vim in folder /autoload.
- Unite and Vimproc in folder /bundle. 

Vimproc is installed in Pathogen folder Bundle, and then compiled with MinGW. 

MinGW is installed. MinGW is in path variabele. I navigate with cmd.exe to the folder where Vimproc is. 

![screenshot 2014-07-02 21 59 17](https://cloud.githubusercontent.com/assets/5211845/3461471/5a1bbc90-0223-11e4-83f4-7744ce46769d.png)

[See this issue](http://stackoverflow.com/questions/13157068/make-is-not-recognized-as-an-internal-or-external-command-qt-sdk-windows) why I had to use mingw32-make. All the files are compiled. 

When I run 

```
 :Unite file_rec/async
```

I get the message: [file_rec/async] async command : "" is not executable. 
And I get the message that Vimproc is not installed. 

The compiled Vimproc files and Vimproc default files are in the folder bundle/vimproc. bundle/unite works well. So I don't think it is a issue with Pathogen. 

**Screen shot:**
![screenshot 2014-07-02 21 54 14](https://cloud.githubusercontent.com/assets/5211845/3461443/048bdac6-0223-11e4-8a64-db9ea7f0a539.png)

**Comment by kuzmeig1** [comment]
I'm facing the same issue, but with different plugin, called `Quramy/tsuquyomi`. It doesn't work ether with Unite plugin.

This is what I have:

```
| |~vimproc.vim.git/
| | |~autoload/
| | | |+vimproc/
| | | |-fakepoll.h
| | | |-proc.c
| | | |-proc_w32.c
| | | |-ptytty.c
| | | |-ptytty.h
| | | |-vimproc.vim
| | | |-vimproc_win32.dll
| | | `-vimstack.c
| | |+doc/
| | |+plugin/
| | |+test/
| | |+tools/
| | |-make_android.mak
| | |-make_cygwin.mak
| | |-make_mac.mak
| | |-make_mingw32.mak
| | |-make_mingw64.mak
| | |-make_msvc.mak
| | |-make_sunos.mak
| | |-make_unix.mak
| | |-Makefile
| | |-README.mkd
```

**Comment by kuzzmi** [comment]
I'm facing the same issue, but with different plugin, called `Quramy/tsuquyomi`. It doesn't work ether with Unite plugin.

This is what I have:

`Windows 8.1 x64`

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jul 28 2015 20:53:47)
MS-Windows 32-bit console version
Included patches: 1-802
```

```
| |~vimproc.vim.git/
| | |~autoload/
| | | |+vimproc/
| | | |-fakepoll.h
| | | |-proc.c
| | | |-proc_w32.c
| | | |-ptytty.c
| | | |-ptytty.h
| | | |-vimproc.vim
| | | |-vimproc_win32.dll
| | | `-vimstack.c
| | |+doc/
| | |+plugin/
| | |+test/
| | |+tools/
| | |-make_android.mak
| | |-make_cygwin.mak
| | |-make_mac.mak
| | |-make_mingw32.mak
| | |-make_mingw64.mak
| | |-make_msvc.mak
| | |-make_sunos.mak
| | |-make_unix.mak
| | |-Makefile
| | |-README.mkd
```

**Comment by Shougo** [comment]
@kuzzmi It seems Quramy/tsuquyomi 's problem.  I think you should create new issue in it.
