### ISSUE TITLE
I can' t describe the problem, and why generate this problem

### ISSUE THREAD

**Issue by kdurant** [Shougo/vimproc.vim#180]
![11](https://cloud.githubusercontent.com/assets/2704364/5279020/0e836816-7b1b-11e4-8016-68243adf9e11.png)

remove from [neocomplete #324](https://github.com/Shougo/neocomplete.vim/issues/324)

`参数错误` = `parameter error`

`vimproc#version() : 800`
`vimproc#dll_version() : 800`

How check vimproc dll binary 32bit/64bit?

**Comment by Shougo** [comment]
No response...
