### ISSUE TITLE
Easier installation

### ISSUE THREAD

**Issue by maxnordlund** [Shougo/vimproc.vim#186]
To make it easier for new users why not provide a command to run `make` in this plugins directory? Similar to how [vim-go][1] does for installing go binaries, e.g. `:GoInstallBinaries`.

[1]: https://github.com/fatih/vim-go

**Comment by Shougo** [comment]
OK.   I think automatic build is better aproach.
But you cannot build vimproc easily in Windows.
Because, there are many build system in Windows.

**Comment by maxnordlund** [comment]
One way is to try find `make`, and if it isn't in the users path show the user some sort of helpful error message. "Couldn't find make on your system, please see \:help vimproc for more details"

**Comment by maxnordlund** [comment]
By try to find, I mean try some sane default configurations/name of the executable. Maybe look in the usual places that they are installed, e.g. cygwin/mingw/visual studio?

**Comment by Shougo** [comment]
I think it is not easy solution.  Although Pull request is wellcome.

**Comment by maxnordlund** [comment]
I'll take a stab at it this afternoon/evening. See what I can come up with.
