### ISSUE TITLE
On windows vimproc#get_command_name: File is not found.

### ISSUE THREAD

**Issue by kalekseev** [Shougo/vimproc.vim#192]
I use vim-go with neocomplete and it works as it should.
But if I add vimproc like this
```
NeoBundle 'Shougo/vimproc', {
\    'build': {
\        'windows' : 'tools\\update-dll-mingw',
\        'unix': 'make -f make_unix.mak',
\        'mac': 'make -f make_mac.mak',
\    },
\ }
```
I get this error on completiion:
```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
"tmp\hello.go" 30L, 514C
Error occurred calling omnifunction: go#complete#Complete
function neocomplete#handler#_do_auto_complete..neocomplete#complete#_set_results_pos..452..<SNR>197_set_complete_results_pos..go#complete#Complete..<SNR>220_gocodeAutocomplete..<SNR>220_gocodeCommand..<SNR>220_system..vimproc#system2..vimproc#system..<SNR>194_system..vimproc#pgroup_open..<SNR>194_pgroup_open..vimproc#plineopen3..<SNR>194_plineopen..<SNR>194_convert_args..vimproc#get_command_name, line 15
vimproc#get_command_name: File "D:UsersMyUsergobin/gocode" is not found.
match 1 of 2
Back at original
```

Real file path is `D:\Users\MyUser\go\bin\gocode`.
Other plugins seems to work without problem with vimproc, at least NeoBundle works with it without problems.

My setup
  - Windows 7 x64
  - [vim build](https://bitbucket.org/Haroogan/vim-for-windows/overview)
  - [vimrc]( https://github.com/kalekseev/vimfiles/blob/86091b6fddf8b8cc48a914f04f37899d167978d3/vimrc)

**Comment by kalekseev** [comment]
It seems like vim-go calls vimproc with command like that "D:\Users\MyUser\go\bin/gocode"
Should I create vim-go issue for this problem instead?

**Comment by kalekseev** [comment]
I've created pr with fix for vim-go https://github.com/fatih/vim-go/pull/343

**Comment by Shougo** [comment]
> It seems like vim-go calls vimproc with command like that "D:\Users\MyUser\go\bin/gocode"
> Should I create vim-go issue for this problem instead?

Yes.  vim-go must escape `\` to use vimproc.
