### ISSUE TITLE
vimproc folders and dll

### ISSUE THREAD

**Issue by jvillasante** [Shougo/vimproc.vim#193]
Using NeoBundle I see that vimproc is installed on vimproc/ and also vimproc.vim/, in vimproc.vim/ the dll is builded ok, not so on vimproc/ and finally, NeoBundle uses vimproc/ (where there is no dll), not vimproc.vim/

I manually run make on vimproc/ folder and neobundle could install everything ok, but why is vimproc using two different folders??

**Comment by Shougo** [comment]
I think repository name was changed.
Old version is "vimproc", but "vimproc.vim" is now.
You should remove the "vimproc" directory.

> Using NeoBundle I see that vimproc is installed on vimproc/ and also vimproc.vim/, in vimproc.vim/ the dll is builded ok, not so on vimproc/ and finally, NeoBundle uses vimproc/ (where there is no dll), not vimproc.vim/

Please upload your .vimrc.

**Comment by Shougo** [comment]
No response.
