### ISSUE TITLE
Non-specific binary name for 32-bit MinGW

### ISSUE THREAD

**Issue by orlp** [Shougo/vimproc.vim#196]
In `make_mingw32.mak` `CC` is set to `gcc`. It should be `i686-w64-mingw32-gcc`.

Some MinGW installs have a 64-bit exclusive `gcc`, where using `-m32` is an error since it's not multilib.

**Comment by Shougo** [comment]
Well, but ...

https://github.com/Shougo/vimproc.vim/issues/118

> Fixed this by replacing gcc in the makefile with mingw32-gcc

https://github.com/Shougo/vimproc.vim/issues/86

Can you consider the problem?

**Comment by Shougo** [comment]
I cannot decide MinGW binary name.  Because it is chaos.

**Comment by orlp** [comment]
@Shougo https://github.com/Shougo/vimproc.vim/issues/86 suggests the same solution as I did.

Modern MinGW (which is MinGW-w64) 32-bit distributions always come with `i686-w64-mingw32-gcc`. It's the best command to get a 32-bit GCC on windows.

**Comment by k-takata** [comment]
At least, there are three variants:

1. `mingw32-gcc` which comes with the original version of MinGW.
2. `i686-w64-mingw32-gcc` which comes with 32-bit MinGW/w64.
3. `i686-pc-mingw32-gcc` which comes with Cygwin's mingw-gcc package.

I think the default should be `CC=gcc`, and a user should set `PATH` or `CC` properly.

**Comment by orlp** [comment]
@k-takata 

Cygwin is irrelevant, this is about `make_mingw32.mak`, not `make_cygwin.mak`. MinGW is also inferior to MinGW-w64 - this is reflected in `make_mingw64.mak`.

But I think `i686-w64-mingw32-gcc` should be the default, just like that `x86_64-w64-mingw32-gcc` is the default in `make_mingw64.mak`.

**Comment by k-takata** [comment]
> Cygwin is irrelevant,

No. If you want to build Win32 version of vimproc.dll on Cygwin with mingw-gcc (cross compiler) package, you should use `make_mingw32.mak`, not `make_cygwin.mak`.

> this is reflected in make_mingw64.mak.

Because the original MinGW doesn't have 64-bit compiler, we assume that everyone uses MinGW/w64 for 64-bit build.
