### ISSUE TITLE
Got exception vp_pipe_read on cygwin

### ISSUE THREAD

**Issue by nowox** [Shougo/vimproc.vim#198]
I installed vimproc on cygwin with bundle and when I execute

     :VimProcBang ls

I got this result:

```
Error detected while processing function <SNR>8_bang..<SNR>28_read_pgroup..<SNR>28_read_pipes..<SNR>28_r
ead..<SNR>28_vp_pipe_read..<SNR>28_libcall_raw_read:
line   12:
E605: Exception not caught: vimproc: vp_pipe_read: 'read() error: Input/output error'
Error detected while processing function <SNR>8_bang..<SNR>28_read_pgroup..<SNR>28_read_pipes..<SNR>28_r
ead:
line   12:
E170: Missing :endwhile
Error detected while processing function <SNR>8_bang..<SNR>28_read_pgroup:
line    7:
E171: Missing :endif
Error detected while processing function <SNR>8_bang:
line   14:
E171: Missing :endif
Press ENTER or type command to continue
```

I have nothing else in my .vimrc

```
set all&
set nocompatible

filetype off
set  runtimepath +=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'gmarik/Vundle.vim'

Plugin 'Shougo/vimproc.vim'
Plugin 'Shougo/vimshell.vim'

call vundle#end()
filetype plugin on
filetype indent on
```

Same issue with `VimShell` and `ls`

Here's my CYGWIN versions (I tried with both):

```
$ uname -a
CYGWIN_NT-6.3 foo 2.0.2(0.287/5/3) 2015-05-08 17:00 x86_64 Cygwin
CYGWIN_NT-6.3-WOW foo 2.0.2(0.287/5/3) 2015-05-08 17:03 i686 Cygwin

```

I also tried to build vimproc library with `i686-pc-cygwin-gcc`

**Comment by Shougo** [comment]
@k-takata @ichizok Can yout test the problem?

**Comment by nop0x0000** [comment]
Same problem occurs.

**Comment by sc00ter** [comment]
probably need to rebase the dll...
/bin/rebase -s -4 ~/.vim/bundle/vimproc.vim/autoload/vimproc_cygwin.dll

**Comment by k-takata** [comment]
It seems that `vimproc#pgroup_open()` fails when the second parameter (is_pty) is 1.
But I don't know why.

**Comment by Shougo** [comment]
Related problem?

https://github.com/Shougo/vimproc.vim/issues/195

**Comment by nop0x0000** [comment]
I tried follow command. But not resolved.
/bin/rebase -s -8 ~/.vim/bundle/vimproc.vim/autoload/vimproc_cygwin.dll

**Comment by Shougo** [comment]
I have created minimal sample.

`$ gcc -o test test.c -lutil`

You can test it in Cygwin environment.

https://gist.github.com/Shougo/19a478f29c6e7d10124a

**Comment by Shougo** [comment]
Sample output

```
autoload  CONTRIBUTING.md  doc	plugin	README.md  rplugin  run_tests.sh

eof
read = 0
```

**Comment by Shougo** [comment]
I have tested vimproc in Cygwin and fixed the problem.
The error reason "read() returns -1 and pfd.revents is POLLIN".
Why it is occurred in Cygwin...
