### ISSUE TITLE
Invalid expression in self.vimproc.stdout.read()

### ISSUE THREAD

**Issue by ressu** [Shougo/vimproc.vim#200]
I'm getting the following after enabling vimproc:
```
E15: Invalid expression: self.vimproc.stdout.read()
E716: Key not present in Dictionary: vimproc.stdout.read()
E15: Invalid expression: self.vimproc.stdout.read()
E716: Key not present in Dictionary: vimproc.stdout.read()
E15: Invalid expression: self.vimproc.stdout.read()
E716: Key not present in Dictionary: vimproc.stdout.read()^C
Error detected while processing /home/ressu/.vim/bundle/vimproc.vim/plugin/autoload/vimproc/cmd.vim:
```
(After a while I terminated with CTRL-C)

I'm loading vimproc with the NeoBundle recipe using:
``` VimL
NeoBundleRecipe 'vimproc.vim'
```

Disabling vimproc gets rid of the problem.

**Comment by Shougo** [comment]
Please check vimproc is compiled.
Your environment is not Windows?
This routine is for Windows.
Why the error is occurred?
Please upload your minimal config and reproduce ways

**Comment by ressu** [comment]
The environment is Ubuntu Linux. And vimproc has been compiled (recompiled by hand in addition to the automatic compilation by the recipe)

Minimal config to reproduce is
``` VimL
set nocompatible
set runtimepath+=~/.vim/bundle/neobundle.vim/

call neobundle#begin(expand('~/.vim/bundle'))
NeoBundle 'Shougo/vimproc.vim'
call neobundle#end()
NeoBundleCheck
```

The error occurs on startup

**Comment by ressu** [comment]
Hmm.. further inspection reveals that for some reason vimproc is being installed to ~/.vim/bundle/vimproc.vim/plugin which is causing the issue.

Deleting vimproc.vim and allowing the above snippet to install it makes vimproc run properly.
