### ISSUE TITLE
can not compile by vs2015

### ISSUE THREAD

**Issue by foxundermoon** [Shougo/vimproc.vim#201]
this is error message

Microsoft (R) 程序维护实用工具 14.00.23026.0 版
版权所有 (C) Microsoft Corporation。  保留所有权利。

makefile(2) : fatal error U1034: 语法错误: 缺少分隔符
Stop.

**Comment by foxundermoon** [comment]
my os is win10 x64

**Comment by k-takata** [comment]
You seem to run `nmake` without specifying `-f` option. You need also set `SDK_INCLUDE_DIR`.
Check the Windows section in the document: https://github.com/Shougo/vimproc.vim#windows
