### ISSUE TITLE
New data format is broken for vimproc#readdir()

### ISSUE THREAD

**Issue by Shougo** [Shougo/vimproc.vim#209]
https://github.com/Shougo/vimproc.vim/pull/206 is broken.

Test case:

* Create empty directory.
```
$ mkdir -p test/test/test
```

* Get files by `vimproc#readdir()`

`:echo vimproc#readdir('test/test')`, `:echo vimproc#readdir('test/test/test')`

* `vimproc#readdir('test/test/test')` got "test/test/test" file...

**Comment by k-takata** [comment]
Sorry, fixed.
The previous result was returned when a directory was empty.

**Comment by Shougo** [comment]
Thank you!
