### ISSUE TITLE
vp_file_read() error?

### ISSUE THREAD

**Issue by Shougo** [Shougo/vimproc.vim#210]
https://github.com/Shougo/unite.vim/issues/1020

It seems `vp_file_read()` error.
But I don't know why...

**Comment by Shougo** [comment]
It is not vimproc problem.  Closing.

**Comment by Shougo** [comment]
It seems broken in some environments.

**Comment by Shougo** [comment]
To Reproduce

* MacOS X
* Use pipe like vimproc#system()
* Empty result and exit command.

**Comment by ichizok** [comment]
This problem is caused by the command output including null-character.
It seems not to depend on environment.

to reproduce:

```vim
:call vimproc#system('printf "\0"')
```

detail:

In this case, `vp_fd_read()` sets `_result.buf` as follow: 

```
ff 80 80 80 80 81 00 ff 80 80 80 80 81 30 00 ...
                  ^^ output            ^^ eof flag  
```

Vim script can only treat up to `ff 80 80 80 80 81 00`, thus it cannot parse `eof` flag.

**Comment by k-takata** [comment]
How was NUL handled before the new data format?

**Comment by ichizok** [comment]
In previous code, it doesn't handle NUL.
(so I placed output data in tail of result: `EOV | EOF | DATA...`

**Comment by k-takata** [comment]
Ah! So I have to do the same thing with the new data format.

**Comment by Shougo** [comment]
Thanks!
