### ISSUE TITLE
Add Call Back or Reminder When Command Finished

### ISSUE THREAD

**Issue by j5shi** [Shougo/vimproc.vim#212]
Hi,

I want to get an reminder when the task which is executed by `vimproc#system()` (or similiar interfaces) is finished, so I can do something else after it, e.g. to execute a vim command which can't be executed with Vimproc.

Or can Vimproc support execute Vim command in another process?

Or can Vimproc support call back function (command) when a task is done?

Thanks.

**Comment by Shougo** [comment]
No.  It is not vimproc's work.
You should use vimproc wrapper like vital-process-manager.
https://github.com/vim-jp/vital.vim/blob/master/doc/vital-process_manager.txt

**Comment by j5shi** [comment]
Well, vital.vim is too big a plugin and I don't use 99% of its functionalities. Anyway, thanks for your recommendation.

**Comment by Shougo** [comment]
You can only include the needed modules.
So, you don't have to concern the huge.
