### ISSUE TITLE
E121: Undefined variable: fdlist

### ISSUE THREAD

**Issue by mattia72** [Shougo/vimproc.vim#215]
Since I've updated vimproc, I get the following error, if I want to install something with neobundle:
```
...
[vimproc] Vim(let):E364: Library call failed for "vp_pipe_open()"
[vimproc] Error occurred in calling s:vp_pipe_open()
...
Error detected while processing function neobundle#commands#check..neobundle#commands#install..<SNR>25_install..neobundle#installer#sync..vimproc#pgroup_open..<SNR>140_pgroup_open..vimproc#plineopen2..<SNR>140_plineopen..<SNR>140_vp_pipe_open:
line   25:
E121: Undefined variable: fdlist
Error detected while processing function neobundle#commands#check..neobundle#commands#install..<SNR>25_install..neobundle#installer#sync..vimproc#pgroup_open..<SNR>140_pgroup_open..vimproc#plineopen2..<SNR>140_plineopen..<SNR>140_vp_pipe_open:
line   25:
E116: Invalid arguments for function len(fdlist)
...
```
The same error comes if I try `:echo vimproc#system('dir')`
I'm working on Win7 32. I've built vimproc_win32.dll with mingw.
`:echo vimproc#version() ` returns 
```
900
```
`:echo vimproc#dll_version()` returns
```
E364: Library call failed for "vp_dlversion()" 
```

**Comment by Shougo** [comment]
Your vimproc binary is broken.
You should rebuild it.

**Comment by mattia72** [comment]
The merged pull request #216 from k-takata/fix-210 corrects this issue.
The issue can be closed! Thank you!

**Comment by j5shi** [comment]
I had the same problem since I updated to version 9.3

**Comment by k-takata** [comment]
Please make sure that the vimproc binary is properly updated. The binary is not compatible with version 9.2.
