### ISSUE TITLE
vim crashes running let sock = vimproc#socket_open('www.yahoo.com', 80)

### ISSUE THREAD

**Issue by kraxli** [Shougo/vimproc.vim#228]
The command "let sock = vimproc#socket_open('www.yahoo.com', 80)" lets crash 

What works from the examples is:
let file = vimproc#fopen("./test1.vim", "O_RDONLY", 0)
and
let sub = vimproc#popen2('dir')

I am working with vim 7.4 (x64) including patches 1-417 on windows 7 (x64). I compiled vimproc with mingw32_64 which compiles fine but also tried the binaries from https://github.com/Shougo/vimproc.vim/releases. The latter binaries produce the same error.

I would be grateful for any help! Is my problem related to issue #208 (I did not manage do extract the 7z-file from https://tuxproject.de/projects/vim/)?

**Comment by Shougo** [comment]
OK, I will test it.
But I cannot reproduce the problem in my Linux environment.

I will test it in Windows 7 environment later.

**Comment by Shougo** [comment]
> I would be grateful for any help! Is my problem related to issue #208 (I did not manage do extract the 7z-file from https://tuxproject.de/projects/vim/)?

No.  It is Vim and popen problem.  And your Vim is 7.4.417...

**Comment by Shougo** [comment]
Unfortunately, I cannot reproduce the problem.
@k-takata Can you test it?

Vim 7.4.417 is too old.  Please test latest Vim binary.

**Comment by kraxli** [comment]
thanks I will recompile a higher version of vim.

**Comment by kraxli** [comment]
I now downloaded vim 7.4.898 (x64) from https://tuxproject.de/projects/vim/ and it does not crash anymore :-) .
The error I get now is:

Error detected while processing function vimproc#socket_open[1]..<SNR>122_vp_socket_open[1]..<SNR>122_libcall:
line    1:
E364: Library call failed for "vp_socket_open()"
Error detected while processing function vimproc#socket_open[1]..<SNR>122_vp_socket_open:
line    1:
E688: More targets than List items
line    2:
E121: Undefined variable: socket
E15: Invalid expression: socket

I'll have a look at this or just does anybody has any spontaneous hints where to look into?

**Comment by Shougo** [comment]
@kraxli 
`s:vp_socket_open` results are empty.
Please upload the variables in `s:libcall()` like this.

```vim
function! s:libcall(func, args) "{{{
  let stack_buf = libcall(g:vimproc#dll_path, a:func, s:encode_list(a:args))
  echomsg string(stack_buf)
  if empty(stack_buf)
    return []
  endif
  let [result, err] = s:decode_list(stack_buf)
  echomsg string([result, err])
  if err
    let s:lasterr = result
    let msg = vimproc#util#iconv(string(result),
          \ vimproc#util#systemencoding(), &encoding)

    throw printf('vimproc: %s: %s', a:func, msg)
  endif
  return result
endfunction"}}}

```

**Comment by kraxli** [comment]
@Shougo: thanks for comming back on that! Calling 

    vimproc#socket_open('www.yahoo.com', 80)

calls 

    function! s:vp_socket_open(host, port)
      let [socket] = s:libcall('vp_socket_open', [a:host, a:port])
      return socket
    endfunction  

which should update s:libcall ...

**Comment by Shougo** [comment]
Please change `s:libcall()` definition in autoload/vimproc.vim.
It is line 1247.

**Comment by kraxli** [comment]
sure I did - sorry for not having said that. I get the same error as before with some additional messages containing binary code. 
 Just in case it is of any interest (I cannot do learn anything from it):

```viml
'<ff><80><80><80><80><90>0000000070140000<ff>'
[['0000000070140000'], 0]
'<ff><80><80><80><80><89>SIGABRT:1<ff><80><80><80><80><88>SIGFPE:2<ff><80><80><80><80><88>SIGILL:3<ff><80><80><80><80><88>SIGINT:4<ff><80><80><80><80><89>SIGSEGV:5<ff><80><80><80><
80><89>SIGTERM:6<ff><80><80><80><80><89>SIGALRM:7<ff><80><80><80><80><89>SIGCHLD:8<ff><80><80><80><80><89>SIGCONT:9<ff><80><80><80><80><89>SIGHUP:10<ff><80><80><80><80><8a>SIGKILL:
11<ff><80><80><80><80><8a>SIGPIPE:12<ff><80><80><80><80><8a>SIGQUIT:13<ff><80><80><80><80><8a>SIGSTOP:14<ff><80><80><80><80><8a>SIGTSTP:15<ff><80><80><80><80><8a>SIGTTIN:16<ff><80>
<80><80><80><8a>SIGTTOU:17<ff><80><80><80><80><8a>SIGUSR1:18<ff><80><80><80><80><8a>SIGUSR2:19<ff>'
[['SIGABRT:1', 'SIGFPE:2', 'SIGILL:3', 'SIGINT:4', 'SIGSEGV:5', 'SIGTERM:6', 'SIGALRM:7', 'SIGCHLD:8', 'SIGCONT:9', 'SIGHUP:10', 'SIGKILL:11', 'SIGPIPE:12', 'SIGQUIT:13', 'SIGSTOP:
14', 'SIGTSTP:15', 'SIGTTIN:16', 'SIGTTOU:17', 'SIGUSR1:18', 'SIGUSR2:19'], 0]
'<ff><80><80><80><80><84> 902<ff>'
[[' 902'], 0]
Error detected while processing function vimproc#socket_open[1]..<SNR>124_vp_socket_open[1]..<SNR>124_libcall:
line    1:
E364: Library call failed for "vp_socket_open()"
''
Error detected while processing function vimproc#socket_open[1]..<SNR>124_vp_socket_open:
line    1:
E688: More targets than List items
line    2:
E121: Undefined variable: socket
E15: Invalid expression: socket
```

**Comment by Shougo** [comment]
OK.  I get it.
Your "vp_socket_open()" is broken.  But I don't know why.
Can you check vimproc in 32bit version using Vim 32bit version?

**Comment by Shougo** [comment]
And please test Kaoriya Vim.

http://www.kaoriya.net/software/vim/

**Comment by k-takata** [comment]
I got the same error when I tried to connect to a nonexistent server, but I couldn't reproduce when I connected  to 'www.yahoo.com'.

**Comment by Shougo** [comment]
OK.  It seems "vp_socket_open()" problem.
@k-takata  Can you fix it?

**Comment by Shougo** [comment]
I have reproduced the problem using non existent server...
I will research it.

**Comment by Shougo** [comment]
The problem was reproduced in Unix environment.
I have added the check.
