### ISSUE TITLE
E370: Could not load library iconv.dll

### ISSUE THREAD

**Issue by j5shi** [Shougo/vimproc.vim#231]
I'm suffering from a Vim random crash problem so I tried to find out which plugin that caused the crash, but so far I haven't got a conclusion. I see this error from `vimproc#util#iconv` which I don't know if it will cause fatal error on Windows .

> E370: Could not load library iconv.dll

The comments seem saying that missing conv.dll is ok

>   " On Windows, some encodings can be converted by iconv() even if
>   " libiconv.dll is not available.

My question is: should I ignore E370?

**Comment by Shougo** [comment]
Is iconv library already installed?

**Comment by j5shi** [comment]
After I raised this issue, I installed `iconv.dll`, and I experienced a random crash again after I installed `iconv.dll`. So maybe this was not the problem.

By the way, do you have any suggestions in debugging random Vim crash, the crash happened all of a sudden, without any error prints.

**Comment by Shougo** [comment]
I think it is not vimproc issue.  I will close it.

> By the way, do you have any suggestions in debugging random Vim crash, the crash happened all of a sudden, without any error prints.

I think you should ask it in vim_dev.

**Comment by j5shi** [comment]
Thanks.
