### ISSUE TITLE
Neobundle could give a hint about missing gcc

### ISSUE THREAD

**Issue by xliiv** [Shougo/vimproc.vim#237]
NeoBundle installer (https://github.com/Shougo/vimproc.vim#neobundle)
exits with no hint when gcc (linux) is not installed.

**Comment by Shougo** [comment]
Oh, it is the Makefile problem.
It should be fixed.

**Comment by Shougo** [comment]
@k-takata @ichizok Can you add the error check?

**Comment by k-takata** [comment]
Isn't it the matter of NeoBundle?
When setting a wrong value to `$CC`, `make` shows some errors like this:

```
$ make CC=foo
make -f make_unix.mak
make[1]: Entering directory `/home/ken/vimproc.vim'
foo -W -O2 -Wall -Wno-unused -Wno-unused-parameter -std=gnu99 -pedantic -shared -fPIC -o lib/vimproc_linux64.so src/proc.c -lutil
make[1]: foo: Command not found
make[1]: *** [lib/vimproc_linux64.so] Error 127
make[1]: Leaving directory `/home/ken/vimproc.vim'
make: *** [all] Error 2
```

Note that `make[1]: foo: Command not found` will be outputted to stderr instead of stdout.

**Comment by Shougo** [comment]
OK.  It seems neobundle issue.
Please create new issue in neobundle.
And please create minimal .vimrc.
