### ISSUE TITLE
[vimproc] vimproc's DLL: "../../.vim/plugged/vimproc.vim/lib/...roc_linux64.so" is not found.  Please read :help vimproc and make it.

### ISSUE THREAD

**Issue by adham90** [Shougo/vimproc.vim#238]
i use ubuntu 14.04 i have this msg when i run `make` command
```
make -f make_unix.mak
make[1]: Entering directory `/home/adham/.vim/bundle/vimproc.vim'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/home/adham/.vim/bundle/vimproc.vim'
```
and i have this msg in vim command line
```
[vimproc] vimproc's DLL: "/home/adham/.vim/plugged/vimproc.vim/lib/...roc_linux64.so" is not found.  Please read :help vimproc and make it.
```

**Comment by k-takata** [comment]
It seems that you have two local copies of vimproc: under ~/.vim/bundle and ~/.vim/plugged.

**Comment by adham90** [comment]
oh, so should i delete one of them or it's okay?
the problem was fixed by running `make` under `.vim/plugged/vimproc.vim/` dir **thx** @k-takata

**Comment by k-takata** [comment]
Maybe you can delete it, but it depends on your plugin manager settings.

**Comment by Shougo** [comment]
It is solved.
Closing.

**Comment by xahon** [comment]
When using `vim-plug` `make` solves problem in `~/.vim/plugins/vimproc.vim` as @k-takata mentioned
