### ISSUE TITLE
vimproc#system() returns different result compared to builtin system()

### ISSUE THREAD

**Issue by lambdalisue** [Shougo/vimproc.vim#239]
With vimproc 9.2, Vim 7.4.1246 in Ubuntu 15 (64bit).

```vim
echo printf('"%s"', system('echo @{upstream}'))
echo printf('"%s"', vimproc#system('echo @{upstream}'))
```

The code above show

```
"@{upstream}
"
"@u @p @s @t @r @e @a @m
"
```

As long as `vimproc#system()` is an alternative method of builtin `system()`, the result should be equal.
Additionally, I guess that you handle `{}` because of `${VARIABLE}` context. If so you probably need to handle `{}` only when the leading character is `$` (or is there anything what I don't know?)

**Comment by lambdalisue** [comment]
`:h vimshell-tips-block`

**Comment by Shougo** [comment]
Yes, it is feature.
And zsh same behaves.
