### ISSUE TITLE
vimproc is blocking UI

### ISSUE THREAD

**Issue by noscript** [Shougo/vimproc.vim#240]
Perhaps I misunderstand the purpose of **vimproc** but in both cases I get the same blocking behavior, I can't use vim till command finishes or I hit <kbd>^C</kbd>:

```vim
:VimProcBang sleep 10 ; echo 'hello'
:!sleep 10 ; echo 'hello'
```

**Comment by wsdjeg** [comment]
so you think it is not asynchronous?

**Comment by noscript** [comment]
Yes, I think it's not asynchronous.

https://en.wikipedia.org/wiki/Asynchrony_%28computer_programming%29
> ...without the program blocking to wait for results...

**Comment by wsdjeg** [comment]
but I think it is just because vimproc need CursorHold for data output

**Comment by noscript** [comment]
There is no mention of `CursorHold` in vimproc documentation. Besides, my vim build does support `CursorHold`.

Is this expected vimproc behavior? If so, is there any advantage of using `:VimProcBang` over `!:`

**Comment by wsdjeg** [comment]
if you are using vim in terminal ,you will find ,they are different,
`:! sleep 10;` will blocking in terminal
`:VimProcBang sleep 10;` only block current vim windows

**Comment by wsdjeg** [comment]
and if you are using tmux,after `VimProcBang` you also can switch to next ot preview windows

**Comment by Shougo** [comment]
Yes, it blocks the UI.
It is the feature and no mean to implement asynchronous.
