### ISSUE TITLE
Cannot download DLL with proxy

### ISSUE THREAD

**Issue by portown** [Shougo/vimproc.vim#244]
プロキシ環境下＆Powershellが有効な状態で
g:vimproc#download_windows_dll = 1
を指定するとDLLのダウンロードに失敗します。
PowershellのWebClientにプロキシ情報を設定できていないためです。

curlなら.curlrcにプロキシ設定を書いておくことでダウンロード可能になるのですが、
現在のロジックが「Powershellが有効なら（curl有効・無効にかかわらず）Powershellを使う」となっているため、
curlを優先的に使用することができません。

Powershell使用時にプロキシ情報を設定できるようにするか、
オプションでcurlを優先的に使用できるようにしていただけないでしょうか。

**Comment by Shougo** [comment]
@thinca Ping

**Comment by thinca** [comment]
一番てっとり早いのは、デフォルトで `curl` を優先で使うようにする方法かと思います。それで問題なければすぐにできます。

**Comment by Shougo** [comment]
@thinca ではとりあえず、それで実装してもらえますか。
