### ISSUE TITLE
vimproc plugin is not installed

### ISSUE THREAD

**Issue by HackToday** [Shougo/vimproc.vim#246]
Follow readme,

```
git clone https://github.com/Shougo/vimproc.vim.git ~/.vim/bundle/vimproc.vim
cd ~/.vim/bundle/vimproc.vim
make
```

start a vim, and run
`:Unite grep:.`, it said "vimproc plugin is not installed"

Other plugins are managed with Vundle. Other plugins work well.

Not sure why it not work

**Comment by HackToday** [comment]
ping @Shougo  Could you help this ?  Thanks

**Comment by Shougo** [comment]
@HackToday Please check the vimproc plugin is loaded.
You should check your 'runtimepath'.
Vundle only adds the runtimepaths installed by Vundle.

**Comment by HackToday** [comment]
@Shougo  vimproc can not work with Vundle, I tried install Pathogen it solved it.

Also https://github.com/Shougo/vimproc.vim not said it support Vundle, so I think it is not supported.

**Comment by k-takata** [comment]
> vimproc can not work with Vundle,

I haven't used Vundle, but I think vimproc should work with Vundle.
How did you setup Vundle and what error did you get?
(Note that you need to build the vimproc's shared library manually when you use Vundle.)

**Comment by HackToday** [comment]
Hi @k-takata 
I tried following: in .virmc it had

```
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

" custom plugins
Plugin 'shougo/unite.vim'
Plugin 'fatih/vim-go'
Plugin 'majutsushi/tagbar'
Plugin 'shougo/neocomplete.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'bling/vim-airline'
Plugin 'tpope/vim-fugitive'
Plugin 'jistr/vim-nerdtree-tabs'
Plugin 'mbbill/undotree'
Plugin 'Lokaltog/vim-easymotion'
Plugin 'scrooloose/nerdcommenter'

" all of your Plugins must be added before the following line
call vundle#end()            " required
```


The shougo/unite.vim need vimproc to work with grep functions, but when execute

:Unite grep:.

it said vimproc plugin is not installed.

Could you give me clear instruction how to install vimproc with Vundle.  I could try your steps.  Thanks

**Comment by HackToday** [comment]
Like what I  said, I have done 
```
git clone https://github.com/Shougo/vimproc.vim.git ~/.vim/bundle/vimproc.vim
cd ~/.vim/bundle/vimproc.vim
make

```

**Comment by k-takata** [comment]
You need to add a line `Plugin 'Shougo/vimproc.vim'` in the .vimrc.

**Comment by HackToday** [comment]
@k-takata  I tried you said, but hit new errors below:


```
[unite.vim] function <SNR>16_call_unite[33]..unite#start[1]..unite#start#standard[39]..unite#init#_current_unite[118]..unite#helper#call_hook, line 12
[unite.vim] Vim(call):E924: can't have both a "self" dict and a partial: 365
[unite.vim] Error occurred in calling hook "on_init"!
[unite.vim] Source name is grep
Error detected while processing function <SNR>16_call_unite[33]..unite#start[1]..unite#start#standard[50]..unite#candidates#_recache[74]..<SNR>107_recache_candidates_loop[3]..unite#util#strchars[1
]..<SNR>94_get_string[2]..<SNR>96_import[11]..<SNR>96__import[20]..<SNR>96__build_module:
line   18:
E924: can't have both a "self" dict and a partial: <SNR>96_load
Press ENTER or type command to continue
```

**Comment by k-takata** [comment]
> E924: can't have both a "self" dict and a partial: <SNR>96_load

Which version of Vim do you use?
The latest Vim seems to have some problems: vim/vim#690, vim/vim#691
Please try with 7.4.1558 or earlier.

**Comment by HackToday** [comment]
Yes, @k-takata   I tried 7.4.1558, it not have issue.

Thanks

**Comment by msto** [comment]
Hi @k-takata,

Just wanted to thank you for linking to my issue here, reverting to 7.4.1558 solved that for me as well.

**Comment by Shougo** [comment]
I cannot reproduce the problem in 7.4.1583.
Please update it.

**Comment by HackToday** [comment]
@Shougo  I am not sure what extra need to update here, Errors all paste above.

**Comment by k-takata** [comment]
You don't need to update if you don't need to use the latest Vim.
Recent Vim (after channel is introduced with 7.4.1169) is unstable and it should be consider as alpha version, I think.
If you need stable version, you should keep using older one.
