### ISSUE TITLE
release .dll doesn't load correctly

### ISSUE THREAD

**Issue by prabirshrestha** [Shougo/vimproc.vim#247]
Seems like https://github.com/Shougo/vimproc.vim/releases/download/ver.9.2/vimproc_win64.dll doesn't load any more correctly. I had to rebuild the .dll

Would it be possible to create a new release and upload it?

**Comment by Shougo** [comment]
Hm.  It seems Appveyor problem.

**Comment by Shougo** [comment]
But you can get it automatically.
`:help g:vimproc#download_windows_dll`
