### ISSUE TITLE
Stop to use files.kaoriya.net to download vim

### ISSUE THREAD

**Issue by k-takata** [Shougo/vimproc.vim#248]
Now https://github.com/koron/vim-kaoriya/releases is available.

See:
thinca/vim-themis#32
vim-jp/vital.vim#416

**Comment by Shougo** [comment]
Thank you.  Fixed.

**Comment by k-takata** [comment]
おや、バージョン固定してしまいましたか。

**Comment by Shougo** [comment]
はい。もっと良い方法がありますでしょうか

**Comment by k-takata** [comment]
themisでやっているように、 http://vim-jp.org/redirects/ 経由にするのが良いと思われます。
ただし、.bat内でダウンロードしているのを、appveyor.ymlに移して、powershellを使うようにする必要があるので、ちょっと面倒なのですが。

**Comment by Shougo** [comment]
なるほど……。ちょっとそれは複雑になるので他の人に任せたいです。
