### ISSUE TITLE
Installation with dein issue is normal?

### ISSUE THREAD

**Issue by EmilRehnberg** [Shougo/vimproc.vim#251]
I used `dein` to install `vimshell` and noticed I needed `vimproc` as well.

After installing vimproc with dein I would get the error message below

```
[vimproc] vimproc's DLL: "~/.config/nvim/.dein/lib/vimproc_mac.so" is not found.  Please read :help vimproc and make it.
E216: No such group or event: filetypedetect *
Error occurred while loading vimproc.
Please install vimproc Ver.6.0 or above.
Press ENTER or type command to continue
```

I copied `vimproc_mac.so` over to `~/.config/nvim/.dein/lib/` to make it work. Is something messed up with my set-up or is there something missing (in README or installation-process)?

I use `NVIM 0.1.3`

**Comment by Shougo** [comment]
@EmilRehnberg You need the build attribute.

```vim
call dein#add('Shougo/vimproc.vim', {'build': 'make'})
```
