### ISSUE TITLE
"vimproc#get_command_name: File is not found" on windows

### ISSUE THREAD

**Issue by jsfaint** [Shougo/vimproc.vim#264]
Hello @Shougo 

When I call vimproc#system() function on windows with this command
![image](https://cloud.githubusercontent.com/assets/571829/17690338/6c6b2c7c-63c0-11e6-9874-4442e283b8d8.png)
I will get the following message.
![image](https://cloud.githubusercontent.com/assets/571829/17690439/448ab730-63c1-11e6-9ad8-a94ac8014a65.png)

It looks like the shellslash issue. 

My question is: do I need to replace \ to / by myself or it's an issue in vimproc?
This issue is meet when I using vim-go on windows, so if it's not issue in vimproc, I'll report it to [vim-go](https://github.com/fatih/vim-go)

Thanks :smile:

**Comment by Shougo** [comment]
> My question is: do I need to replace \ to / by myself or it's an issue in vimproc?

Yes.  You must convert it.

**Comment by jsfaint** [comment]
Got it, thank you @Shougo
