### ISSUE TITLE
Compatibility layer using a Neovim remote plugin?

### ISSUE THREAD

**Issue by thalesmello** [Shougo/vimproc.vim#265]
This is just speculation, but would it make sense to create a compatibility layer between vimproc's api that uses Neovim's remote plugin feature?

Could it make Unite's sources work better with Neovim, [avoiding segfaults](https://github.com/neovim/neovim/issues/5234)? (I know this is a Neovim bug in itself, but I will think a discussion about compatibility with Neovim could be interesting)

In the least, it would enable Neovim users to use Vimproc compatible plugins without having to build the entire project.

**Comment by Shougo** [comment]
No.
vimproc plugin will be deprecated.

> Could it make Unite's sources work better with Neovim, avoiding segfaults? (I know this is a Neovim bug in itself, but I will think a discussion about compatibility with Neovim could be interesting)

You should use denite.nvim instead.
https://github.com/Shougo/denite.nvim
