### ISSUE TITLE
can not build   vimproc's native extensions 

### ISSUE THREAD

**Issue by moreoronce** [Shougo/vimproc.vim#266]
vim version : 8.0 64-bit
and i tried this command `mingw32-make -f make_mingw64.mak`

and get message below

x86_64-w64-mingw32-gcc -O2 -Wall -shared -m64 -o lib/vimproc_win64.dll src/proc_w32.c -lwsock32
process_begin: CreateProcess(NULL, x86_64-w64-mingw32-gcc -O2 -Wall -shared -m64 -o lib/vimproc_win64.dll src/proc_w32.c
 -lwsock32, ...) failed.
make (e=2):
make_mingw64.mak:12: recipe for target 'lib/vimproc_win64.dll' failed
mingw32-make: *** [lib/vimproc_win64.dll] Error 2

**Comment by k-takata** [comment]
Please make sure that `x86_64-w64-mingw32-gcc` is in the PATH.

**Comment by k-takata** [comment]
No feedback. Closing.
