### ISSUE TITLE
Support passing Environment Variables to subprocesses 

### ISSUE THREAD

**Issue by daltonmatos** [Shougo/vimproc.vim#268]
Hello @Shougo !

[vim-vebugger](https://github.com/idanarye/vim-vebugger) uses `vimproc.vim` to make it possible have a integrated debugger into vim. It's very useful to, sometimes, debug a code passing envvars and vim-vebugger uses `vimproc#ptyopen()` which uses `execv()` which does not support envvars.

Is there any way to currently pass a set of environ variable to the called subprocess? If not, do you think it would be difficult to implement?

Thanks,

**Comment by Shougo** [comment]
Sorry, I don't want to add the feature.
You can emulate the behavior by below code.

```vim
let env_save = $ENV
try
  let $ENV = some_value
  call vimproc#ptyopen()
finally
  $ENV = env_save
endtry
```

**Comment by daltonmatos** [comment]
That's great @Shougo !

Thanks for the suggestion, I will use it, will do the job!

Thanks,
