### ISSUE TITLE
Windows binaries out of date?

### ISSUE THREAD

**Issue by dimxdim** [Shougo/vimproc.vim#269]
First of all, thank you for the wonderful software!

I notice that the latest release of binaries for windows is on Oct 12, 2015, but the latest change in the .c source files is on Jul 29, 2016 (fixing some timing issues on windows).
Is it possible to update the binaries (by issuing a new release maybe?)

Also does anyone know whether binaries included in [Kaoriya](https://github.com/koron/vim-kaoriya/releases) build are the **_latest_** and **_without external patches to vimproc_**, so that maybe someone could just copy the dll from them (it's in their vim's plugins\vimproc\lib directory).

The reason I'm asking is that Kaoriya seems to be quite popular in Japan and presumably well-tested, so it would be nice to have well-tested binaries. Not sure what their compiler is though and how much does it matter.

Thank you in advance!

UPDATE:
On Win10 x64 and vim 64bit latest build from github (also on vim 64bit from tuxproject) both the release and Kaoriya's vimproc_win64.dll results in the following error when entering `:echo vimproc#system('dir')`.
That means that just taking kaoria's dll will not work...

```
Error detected while processing function <SNR>74_vp_dlopen[1]..<SNR>74_libcall:
line    1:
E364: Library call failed for "vp_dlopen()"
Error detected while processing function <SNR>74_vp_dlopen:
line    1:
E714: List required
[vimproc] function vimproc#dll_version[1]..<SNR>74_libcall, line 1
[vimproc] Vim(let):E364: Library call failed for "vp_dlversion()"
[vimproc] Your vimproc binary is not compatible with this vimproc!
[vimproc] Please re-compile it.
[vimproc] function vimproc#system[25]..<SNR>74_system[10]..vimproc#pgroup_open[15]..<SNR>74_pgroup_open[7]..vimproc#plineopen3[6]..<SNR>74_plineopen[64]..<SNR>74_vp_pipe_open[7]..<SNR>74_libcall, line 1
[vimproc] Vim(let):E364: Library call failed for "vp_pipe_open()"
[vimproc] Error occurred in calling s:vp_pipe_open()
[vimproc] a:argv = ['cmd', '/c', 'dir']
[vimproc] original a:argv = ['cmd', '/c', 'dir']
[vimproc] Vim(if):E121: Undefined variable: fdlist
```
UPDATE2: Managed to compile the 64bit dll (under Win10 x64 with the latest Visual Studio 2017 compiler). This dll runs without error so far on all 64bit vim builds, including github, tux and kaoriya. Steps:

```
" On win10 to install win 7.1 sdk:
" https://stackoverflow.com/questions/32091593/cannot-install-windows-sdk-7-1-on-windows-10

To build to go Start->Visual Studio->x64 native tools command prompt
so that it includes all the needed paths. For win32.mak to be found:
$ SET INCLUDE=%INCLUDE%;C:\Program Files\Microsoft SDKs\Windows\v7.1\Include
$ nmake -f make_msvc.mak nodebug=1
```

If anyone interested, here is the dll:
https://drive.google.com/open?id=0B9Mey22cegOgSVFZb0JBZXlrZ1E
SHA1: 28426654d3ee0627cfd948539dd12bca06665e60
(Standard disclaimer applies, I'm not responsible if it causes any damage, sets your house on fire, creates a black hole etc etc)
Could not get 32bit version to compile due to linker error, but too lazy to debug.

**Comment by Shougo** [comment]
Why don't you read the documentation?
https://github.com/Shougo/vimproc.vim#windows-binaries

**Comment by Shougo** [comment]
Ver.9.3 is released.

**Comment by dimxdim** [comment]
Thank you very much!

I have read **ALL** the documentation before trying to compile and **always** used the compile commands as described, the 32bit dll fails at linking stage no matter which "tool command prompt" I used (they are regular cmd prompts with added different env. variables there are several in VS: 2 native and 2 cross-comp)

I know you suggest using mingw64, I just wanted to build with microsoft compiler, since in my experience it produces faster binaries (but I suppose in our case there will not be any difference in speed).

Anyway, thanks for updating!
