### ISSUE TITLE
vimproc#system works but vimproc#system_bg doesn't on Windows 10

### ISSUE THREAD

**Issue by svermeulen** [Shougo/vimproc.vim#273]
I am using windows 10 64 bit.

I have a batch script that just contains the line:

```
echo success >%~dp0/log.txt
```

And I find that when I run it like this:

```
call vimproc#system("D:/Temp/vimproctest/test1.bat")
```

It works correctly and the log.txt file is created.

But when I do this:

```
call vimproc#system_bg("D:/Temp/vimproctest/test1.bat")
```

No log file is generated.  It is as if the bat file is not run at all.

**Comment by Shougo** [comment]
The background processes are exited when autocmd `CursorHold` or `BufWritePost`.
You should check the process by the task manager.

**Comment by Shougo** [comment]
`vimproc#system_bg()` closes all fds.
It may affect the problem.

**Comment by Shougo** [comment]
`vimproc#system_bg()` is deprecated feature.
Not recommended to use.
