### ISSUE TITLE
Get the version of vimproc via vim script.

### ISSUE THREAD

**Issue by wsdjeg** [Shougo/vimproc.vim#274]
@Shougo 

Hi, I need a function to get the lib version like `ver.9.3`, with this version I can get the releases info via github V3 APIs, and download the dlls for windows user.

**Comment by k-takata** [comment]
Vimproc can update the dll by itself when `g:vimproc#download_windows_dll` is set to 1.
Isn't it enough?

**Comment by wsdjeg** [comment]
@k-takata Thanks for this info. I will look into it.

**Comment by k-takata** [comment]
The document is here: https://github.com/Shougo/vimproc.vim/blob/e48975075c1b4db46aabdb275030fad46c13bfe4/doc/vimproc.txt#L400-L407

**Comment by wsdjeg** [comment]
Thanks. I got it.
