### ISSUE TITLE
faulty cygwin detection

### ISSUE THREAD

**Issue by mcandre** [Shougo/vimproc.vim#276]
`make` is building the mingw DLL, but when I run `:VimShell`, vimproc complains that the vimproc cygwin DLL is missing. So there is some kind of conflict there as to whether the environment is mingw vs. cygwin.

**Comment by Shougo** [comment]
https://github.com/Shougo/vimproc.vim/blob/master/Makefile#L3

You can check the Makefile detection.
I don't have Cygwin environment.
Please fix the detection and send PR.

**Comment by k-takata** [comment]
Not enough information and no feedback. Closing.
