### ISSUE TITLE
async stdout/stdin support

### ISSUE THREAD

**Issue by prabirshrestha** [Shougo/vimproc.vim#282]
Is there a support for async stdout/stdin support? Would like to have it supported due to this bug. https://github.com/vim/vim/issues/2548

**Comment by prabirshrestha** [comment]
Basically I would like to have the neovim job-control apis equivalent for vimproc which can be used in vim8 i.e., `job_start`, `job_send`, `job_stop`, `on_stdout`, `on_stderr`, `on_exit`. Currently vim 8 has a deadlock bug which makes it using jobs in vim8 useless in a reasonable ~1000k lines of code since it hangs.

I has also wanted to add fallback support to it in https://github.com/prabirshrestha/async.vim.

**Comment by Shougo** [comment]
OK.  But vimproc does not have callback feature like Vim8.
You need to polling to get outputs.
