### ISSUE TITLE
[Question] How to work with an interactive process?

### ISSUE THREAD

**Issue by tommcdo** [Shougo/vimproc.vim#285]
I'm trying to use vimproc.vim to interact with `jdb` (the Java debugger CLI tool). `jdb` runs as an interactive shell after connecting to a project, where the user can issue commands and the shell outputs a response. I've been able to get this to work with vimproc.vim, aside from one issue: I need to give `jdb` time to respond between my `write()` and `read()` calls. Currently I'm doing something like this:

    call jdb.stdin.write("where\n")
    normal gs
    let l:response = jdb.stdout.read()

I'm using the Normal command `gs` to sleep for 1 second to give `jdb` time. Otherwise, my `read()` call returns immediately with no results. While `gs` works reliably, it's not a pleasant experience.

I experimented using the `timeout` parameter to `read()`, but couldn't get it working. Perhaps I didn't try the right things.

Do you have any advice for a better way to do this? Is working with an interactive process something that vimproc.vim aims to support?

**Comment by Shougo** [comment]
I recommend for you to use job/channel feature in Vim8/Neovim instead.

```vim
let l:response = jdb.stdout.read(number, timeout)
```

You must specify both number and timeout.
The default timeout is `100` ms.

**Comment by Shougo** [comment]
timeout means it blocks until timeout is done.
So you should not increase the value.
Because your Vim will be locked.
