### ISSUE TITLE
Would it be possible to use vim job to replace compiled dll?

### ISSUE THREAD

**Issue by skeept** [Shougo/vimproc.vim#288]
I am not sure if possible but I was thinking that maybe with vim8 maybe it would be possible to have the following logic:

if (dll exists) then
   use dll to do the work
else if vim has jobs
   use vim job feature to do the work
else 
   give error
end

I don't know the plugin enough to know if this is viable or not.
But if this works then user doesn't need to compile anything and plugin just works.

**Comment by Shougo** [comment]
I think it should not.
If you use Vim8 plugin, you should use job APIs directly.

**Comment by skeept** [comment]
yes I agree. The problem is I use neocomplete in some machines that I don't have vim with python. neocomplete uses vimproc. So it will give an warning saying to compile the library.

I am not sure other plugins use vimproc as well.
I know you stopped developing neocomplete but I think it still works really well for my needs. Thank you for developing that!
