### ISSUE TITLE
Need Help From Beginner

### ISSUE THREAD

**Issue by dandymilton** [Shougo/vimproc.vim#291]
I tried to install vimproc.vim for power vim but from the manual vimproc.vim must be compiled before it can be used, but when I try to compile many problems that arise, because I am not aware of the c / c ++ language, this is a big problem for me.

I followed the guide in every issue on github and followed the step-by-step tutorial of searching from Google, I tried installing gcc and his friends from cygwin and mingw but always failed to download, I tried other ways by following the guidelines in readme.md vimproc.vim but experiencing problems in the command line, often every time I execute it, an error always pops up indicating that the file is missing, even though I have put it in the correct path, I try to install it another way with deim, but I Could not execute .sh file due to exec format error.

of course I'm wrong in executing or following the documented guidelines (readme.md) because I don't understand at all how the compiler and c / c ++ language work, is there a simple guide to my problem?

I want to use vim space as my IDE, I need the vimproc.vim plugin.

**Comment by k-takata** [comment]
What OS? If you use Windows, you can download the prebuilt binaries from the [releases page](https://github.com/Shougo/vimproc.vim/releases).

**Comment by dandymilton** [comment]
> What OS? If you use Windows, you can download the prebuilt binaries from the [releases page](https://github.com/Shougo/vimproc.vim/releases).

ohh I see, thank's for your response.

**Comment by Shougo** [comment]
Close-able?

**Comment by dandymilton** [comment]
> Close-able?

Sorry, worst habit.
