### ISSUE TITLE
Why not implement one .bat which can build this plugin with msvc toolchain?

### ISSUE THREAD

**Issue by jiangjianshan** [Shougo/vimproc.vim#298]
Hello, 

    It's recommend can have a batch file which can build this plugin with msvc toolchain but not mingw. Maybe call it update-dll-msvc.bat. Here is a example but only test at my laptop at Windows 10 64 bit environment :
:: ---------------------------------- begin --------------------------------
@echo off

if "%PROCESSOR_ARCHITECTURE%"=="AMD64" (
    call "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" amd64
    nmake -f make_msvc.mak nodebug=1 CPU=AMD64 "SDK_INCLUDE_DIR=C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Include"
) else (
    call "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" x86
    nmake -f make_msvc.mak nodebug=1 CPU=x86 "SDK_INCLUDE_DIR=C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Include"
)
:: ---------------------------------- end --------------------------------

**Comment by Shougo** [comment]
Because I don't use msvc toolchain.
You can create PR.

**Comment by jiangjianshan** [comment]
@Shougo , I have just created one pull request for it. It is "Add batch file to support build with msvc toolchain #299".

**Comment by Shougo** [comment]
Fixed by #299
