### ISSUE TITLE
(mach-o file, but is an incompatible architecture (have 'arm64', need 'arm64e')), '/usr/lib/vimproc_mac.so' (no such file)"

### ISSUE THREAD

**Issue by whitesiroi** [Shougo/vimproc.vim#305]
I moved to M1 MacOS Monterey 12.1 and I started getting this error:

`[vimproc] function quickrun#command#execute[10]..quickrun#run[10]..387[10]..379[1]..vimproc#pgroup_open[15]..<SNR>178_pgroup_open[7]..vimproc#plineopen3[6]..<SNR>178_plineopen[64]..<SNR>178_vp_pipe_open[10]..<SNR>178_libcall, line 1
[vimproc] Vim(let):dlerror = "dlopen(/Users/whitesiroi/.vim/bundle/vimproc.vim/lib/vimproc_mac.so, 0x0005): tried: '/Users/whitesiroi/.vim/bundle/vimproc.vim/lib/vimproc_mac.so' (mach-o file, but is an incompatible architecture (have 'arm64', ne
ed 'arm64e')), '/usr/lib/vimproc_mac.so' (no such file)"
[vimproc] Error occurred in calling s:vp_pipe_open()
[vimproc] a:argv = ['/opt/homebrew/bin/php', '/Users/whitesiroi/Downloads/test/test.php']
[vimproc] original a:argv = ['/opt/homebrew/bin/php', '/Users/whitesiroi/Downloads/test/test.php']
Error detected while processing function quickrun#command#execute[13]..function quickrun#command#execute[10]..quickrun#run[10]..387[10]..379[1]..vimproc#pgroup_open[15]..<SNR>178_pgroup_open[7]..vimproc#plineopen3[6]..<SNR>178_plineopen[64]..<SN
R>178_vp_pipe_open:
line   25:
E121: Undefined variable: fdlist
E116: Invalid arguments for function len(fdlist)`

<img width="1722" alt="vimproc_question" src="https://user-images.githubusercontent.com/1423751/195969110-c40cbeff-82e3-4df2-9dba-e783061fbc1d.png">

`vim --version

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Nov 13 2021 05:05:08)
macOS version - arm64
Included patches: 1-2671, 3402, 3409, 3428, 3489
Compiled by root@apple.com
Normal version without GUI.  Features included (+) or not (-):
+acl               -farsi             +mouse_sgr         +tag_binary
-arabic            +file_in_path      -mouse_sysmouse    -tag_old_static
+autocmd           +find_in_path      -mouse_urxvt       -tag_any_white
+autochdir         +float             +mouse_xterm       -tcl
-autoservername    +folding           +multi_byte        -termguicolors
-balloon_eval      -footer            +multi_lang        +terminal
-balloon_eval_term +fork()            -mzscheme          +terminfo
-browse            -gettext           +netbeans_intg     +termresponse
+builtin_terms     -hangul_input      +num64             +textobjects
+byte_offset       +iconv             +packages          +textprop
+channel           +insert_expand     +path_extra        +timers
+cindent           +ipv6              -perl              +title
-clientserver      +job               +persistent_undo   -toolbar
+clipboard         +jumplist          +popupwin          +user_commands
+cmdline_compl     -keymap            +postscript        -vartabs
+cmdline_hist      +lambda            +printer           +vertsplit
+cmdline_info      -langmap           -profile           +virtualedit
+comments          +libcall           -python            +visual
-conceal           +linebreak         -python3           +visualextra
+cryptv            +lispindent        +quickfix          +viminfo
+cscope            +listcmds          +reltime           +vreplace
+cursorbind        +localmap          -rightleft         +wildignore
+cursorshape       -lua               +ruby/dyn          +wildmenu
+dialog_con        +menu              +scrollbind        +windows
+diff              +mksession         +signs             +writebackup
+digraphs          +modify_fname      +smartindent       -X11
-dnd               +mouse             -sound             -xfontset
-ebcdic            -mouseshape        +spell             -xim
-emacs_tags        -mouse_dec         +startuptime       -xpm
+eval              -mouse_gpm         +statusline        -xsmp
+ex_extra          -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+extra_search      -mouse_netterm     +syntax            -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L/usr/local/lib -o vim        -lm -lncurses  -liconv -framework Cocoa`

I also tried to run it with Rosetta but getting the same error

**Comment by Shougo** [comment]
Please re-build vimproc.
