### ISSUE TITLE
ワイルドカード使用時、シンボリックリンクが解決できていない

### ISSUE THREAD

**Issue by hrsh7th** [Shougo/vimproc.vim#42]
# 前提
/home/user/a は /home/user/test へのシンボリックリンクだとします。

/home
　/user
　　/test
　　　1.txt
　　　2.txt
　　/a => /home/user/test

# 問題
bash では ```ls /home/user/a/*``` を実行すると
```
1.txt 2.txt
```
と表示されますが、vimshell の場合はエラーとなってしまいます。

# 望ましい挙動
bash と同様に、ワイルドカード展開時にもシンボリックリンクを解決してほしいです。

よろしくお願いします。

**Comment by Shougo** [comment]
試したら動作したのでcloseします
