### ISSUE TITLE
Can't compile under Win 7 with MinGW

### ISSUE THREAD

**Issue by NoahTheDuke** [Shougo/vimproc.vim#86]
When I run either of the MinGW makefiles, I get this output:

C:\Users\Noah.vim\bundle\vimproc>make -f make_mingw32.mak
gcc -O2 -Wall -shared -m32 -o autoload/vimproc_win32.dll autoload/proc_w32.c -lw
sock32
process_begin: CreateProcess((null), gcc -O2 -Wall -shared -m32 -o autoload/vimp
roc_win32.dll autoload/proc_w32.c -lwsock32, ...) failed.
make (e=2): The system cannot find the file specified.
make: **\* [autoload/vimproc_win32.dll] Error 2

I've never compiled anything before, so I don't know if I've done something wrong. Have I? What's my next step?

**Comment by codeur4** [comment]
I try to install vimproc an on window 7
My screen on gVim when I run `:VimPocInstall` :
![vimprocinstall](https://cloud.githubusercontent.com/assets/10487632/10107404/16cd837e-63bb-11e5-8f95-0415794a22d6.jpg)
I tried to follow step by step the suggested method by Praful. It don't work and I can't figure out what is the problem. I have the followinf error : 
> make (e=2): the specified file is not found

![vimproc](https://cloud.githubusercontent.com/assets/10487632/10107358/cd45b9ba-63ba-11e5-9a8d-f9f194c41d57.jpg)
Please help

**Comment by Shougo** [comment]
I think gcc is not installed.

**Comment by codeur4** [comment]
I reinstall MinGW from an other source ; I found it [there](http://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/installer/)
I noticed that I have now gcc file in the bin directory. So you were right.
I updated my path and run again `make -f make_mingw32.mak` :
![gcc1](https://cloud.githubusercontent.com/assets/10487632/10116977/bf5ad3a8-6446-11e5-97dd-42ba241ad55d.jpg)
...
![gcc2](https://cloud.githubusercontent.com/assets/10487632/10116978/cac58f94-6446-11e5-9cb1-b48e33329d85.jpg)
But if I do `make -f make_mingw64.mak` :
![gcc3](https://cloud.githubusercontent.com/assets/10487632/10116980/de16f9fc-6446-11e5-8fae-0d6cc08f19be.jpg)
I think it is ok, but if I run `:VimProcInstall` again in Vim I have again :
![vimprocnotfound](https://cloud.githubusercontent.com/assets/10487632/10116988/4ba8a542-6447-11e5-9ee5-4abc4796e4f8.jpg)

I googled 'cannot find -lmsvcrt' but found nothing

**Comment by Shougo** [comment]
You should read the message and the documentation....
Your installed vimproc binary is 32bit.
Because, you executed "make -f make_mingw64.mak" command.
But your Vim is 32bit.  So vimproc binary is not loaded.
You must build 32bit binary.

**Comment by Shougo** [comment]
Hm.  Your used MinGW is broken to build 32bit.
You should use the MinGW binary.

http://tdm-gcc.tdragon.net/download

**Comment by codeur4** [comment]
Ok thank you. 
I ran the first link *tdm-gcc-5.1.0-3.exe*
Now, in my *C:\Tools\TDM-GCC-32\bin* path I have gcc (automatically put in my system path) :
![var_gcc](https://cloud.githubusercontent.com/assets/10487632/10117320/f86d199c-6452-11e5-94ef-9942284a74eb.jpg)
I also remind that I have make (put in my user path) :100: 
![var_make](https://cloud.githubusercontent.com/assets/10487632/10117318/f268ca0a-6452-11e5-8b24-5daae15e24e9.jpg)
that I took from the ruby installer link proposed by Praful :
![mingwinstall](https://cloud.githubusercontent.com/assets/10487632/10117333/5236f84e-6453-11e5-83d9-c9044240868e.jpg)

And now I have :
![result](https://cloud.githubusercontent.com/assets/10487632/10117366/af0b30fc-6454-11e5-95c8-45dbb933441b.jpg)
Is it ok or not, I don't know.
The good thing in Vim is that when I run `:VimProcInstall` I have no error message :
![vimprocinstall](https://cloud.githubusercontent.com/assets/10487632/10117414/8bed54a4-6456-11e5-96e9-a31b831712f3.jpg)
And I have no error when I run the two following commands :
![unitecommand](https://cloud.githubusercontent.com/assets/10487632/10117417/a1ca7e14-6456-11e5-8ca8-1a342f62c957.jpg)
But the first command with async don't show me any proposal and I don't know why.
You think it is an other problem or I have done something wrong ?

**Comment by Shougo** [comment]
You should remove the old vimproc binary.
Reinstall vimproc is recommended.

**Comment by codeur4** [comment]
I have already clean and install VimProc from Vim.
Where can I find the vimproc binary ?

**Comment by codeur4** [comment]
I have suddenly a doubt. Is it the right way to install vimProc with Vundle?
![vundle install](https://cloud.githubusercontent.com/assets/10487632/10118941/a13b2e5e-6487-11e5-8697-9b327a7cb844.jpg)
Or shall I must add something like :
`{'build': {'windows': 'make -f make_mingw32.mak'}}` ?
Well, I tried this :
![plug](https://cloud.githubusercontent.com/assets/10487632/10118987/b1bdf2ba-6488-11e5-8615-0b66bdda3a3b.jpg)
but nothing change.

**Comment by Shougo** [comment]
Hmmm..

Please test vimproc works.
`:echo vimproc#system('dir')`

If vimproc works, it is your async binary problem.

**Comment by codeur4** [comment]
For information I have reinstall vim64 because I run into a windows 64bit system. but the problem still remains the same.
`:echo vimproc#system('dir')` return
![vimprocsystem](https://cloud.githubusercontent.com/assets/10487632/10141378/75bc231a-660c-11e5-8685-9ec0681035a9.jpg)
It works, so according to you it is my async binary.  Do you have an idea how I can fix it?
Thanks for the time you spent with me

**Comment by Shougo** [comment]
Please upload your .vimrc file and please upload unite screenshot using `<Plug>(unite_print_message)` in unite buffer.

**Comment by codeur4** [comment]
I have reinstall vim because I am on a windows 64 bit (sorry for that). I thought vim32 work fine in window64. So now I use vim74-kaoriya-win64.
I have installed MinGW64, changed my path, installed TDM-GCC-64 and changed my path
This is my vimrc at the moment: [vimrc](https://gist.github.com/codeur4/fba59ef300fe15fb8e34)
- I have this following error :
![64](https://cloud.githubusercontent.com/assets/10487632/10170788/f8bfb64e-66d6-11e5-948d-ed2f048fd47a.jpg)
-  and `:echo vimproc#system('dir')` return me now :
![901](https://cloud.githubusercontent.com/assets/10487632/10170829/2825b370-66d7-11e5-80b3-1669052de8d3.jpg)

**Comment by codeur4** [comment]
Here is my [vimrc](https://gist.github.com/codeur4/fba59ef300fe15fb8e34) at the moment.
>please upload unite screenshot using <Plug>(unite_print_message)

How? I looked for `<Plug>(unite_print_message_log)` into unite doc but I don't understand how use it?

**Comment by Shougo** [comment]
OK.  I get it.  You need set `g:unite_source_rec_async_command`.
Please read unite.vim documentation.

```
					*g:unite_source_rec_async_command*
g:unite_source_rec_async_command
		Specify the filelist command and arguments in file_rec/async
		source.  It is arguments List.
>
		" Using ack-grep as recursive command.
		let g:unite_source_rec_async_command =
		\ ['ack', '-f', '--nofilter']

		" Using ag as recursive command.
		let g:unite_source_rec_async_command =
                \ ['ag', '--follow', '--nocolor', '--nogroup',
		\  '--hidden', '-g', '']
<
		The default value is ["find", "-L"] which follows symbolic
		links to have the same behaviour as file_rec, and the
		args(|g:unite_source_rec_find_args|).
		Because, "find" command is fastest.
		Note: In windows environment, you must install file list
		command and specify the variable.
```

**Comment by codeur4** [comment]
Awsome ! 
Thanks
